In [1]:
import numpy as np
from numpy import random

1. Create a 5 x 5 matrix with values ranging from 3 to 7

In [2]:
x = np.arange(3, 8)

for i in x:
     print(x)

[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]


2. Create an array with shape of 4 x 4 and turn it into two arrays along the second axix

In [3]:
y = np.zeros((4,4))
z = np.hsplit(y, 2)
z

[array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])]